export * from './createPatientInterface'
export * from './deletePatientInterface'
export * from './findManyPatientInterface'
export * from './updatePatientInterface'
export * from './findUniquePatientInterface'
